### ISSUE TITLE
Issue after updating to latest version 5.6.1

### ISSUE THREAD

**Issue by abhishekkaura** [xvik/dropwizard-guicey-examples#29]
Hi, My application is failing to start after upgrading to latest version  and working fine with 4.2.2 version

Initialize method 

@Override
  public void initialize(Bootstrap<TestServiceConfig> bootstrap) {
    final Config config = ConfigFactory.load();
    bootstrap.setConfigurationSourceProvider(new FileConfigurationSourceProvider());
    bootstrap.addBundle(GuiceBundle.builder()
        .enableAutoConfig("com.test.platform.audience",
            "com.test.platform.connectors.rest")
        .modules(new AppModule())
        .modules(new HttpClientModule())
        .modules(new SerializationModule())
        .modules(TypesafeConfigModule.fromConfigWithPackage(config, "com.test.platform.audience"))
        .searchCommands()
        .build());
  }

`Exception in thread "main" java.lang.NoClassDefFoundError: org/glassfish/jersey/server/internal/inject/AbstractValueFactoryProvider
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at ru.vyarus.dropwizard.guice.module.installer.scanner.util.OReflectionHelper.getClassesFor(OReflectionHelper.java:55)
        at ru.vyarus.dropwizard.guice.module.installer.scanner.ClasspathScanner.performScan(ClasspathScanner.java:108)
        at ru.vyarus.dropwizard.guice.module.installer.scanner.ClasspathScanner.<init>(ClasspathScanner.java:50)
        at ru.vyarus.dropwizard.guice.module.GuiceyInitializer.<init>(GuiceyInitializer.java:77)
        at ru.vyarus.dropwizard.guice.GuiceBundle.initialize(GuiceBundle.java:116)
        at io.dropwizard.setup.Bootstrap.addBundle(Bootstrap.java:150)
        at com.test.platform.audience.application.TestService.initialize(TestService.java:84)
        at io.dropwizard.Application.run(Application.java:88)
        at com.test.platform.audience.Main.main(Main.java:35)
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.server.internal.inject.AbstractValueFactoryProvider
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 20 more
`

**Comment by xvik** [comment]
Duplicate. Answered in https://github.com/xvik/dropwizard-guicey/issues/252
